In [10]:
from qmiotools.integrations.qiskitqmio import FakeQmio

In [175]:
import sys
from cluster import QPU, Backend, qasm2_to_json
from backend_options import default_backends
from qiskit import qasm2, qasm3
import json, pickle
from qiskit_aer import AerSimulator
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter

In [5]:
from qiskit_aer.noise import NoiseModel

In [19]:
fq = FakeQmio(calibration_file="default_qmio_calibration.json")
type(fq)

Importing calibrations from  default_qmio_calibration.json


qiskit_aer.backends.aer_simulator.AerSimulator

In [23]:
from qmiotools.integrations.qiskitqmio import QmioBackend
qmio=QmioBackend("default_qmio_calibration.json")
noise_model = NoiseModel.from_backend(
        qmio)
noise_model.to_dict()

Importing calibrations from  default_qmio_calibration.json


{'errors': [{'type': 'qerror',
   'id': 'd12b5b4c748d47e1a812cfe55eefdd83',
   'operations': ['sx'],
   'instructions': [[{'name': 'id', 'qubits': [0]},
     {'name': 'kraus',
      'qubits': [0],
      'params': [array([[-0.99977068+0.j,  0.        +0.j],
              [ 0.        +0.j, -0.99737142+0.j]]),
       array([[-0.02141451+0.j,  0.        +0.j],
              [ 0.        +0.j,  0.02146603+0.j]]),
       array([[0.        +0.j, 0.06920588+0.j],
              [0.        +0.j, 0.        +0.j]])]}],
    [{'name': 'x', 'qubits': [0]},
     {'name': 'kraus',
      'qubits': [0],
      'params': [array([[-0.99977068+0.j,  0.        +0.j],
              [ 0.        +0.j, -0.99737142+0.j]]),
       array([[-0.02141451+0.j,  0.        +0.j],
              [ 0.        +0.j,  0.02146603+0.j]]),
       array([[0.        +0.j, 0.06920588+0.j],
              [0.        +0.j, 0.        +0.j]])]}],
    [{'name': 'y', 'qubits': [0]},
     {'name': 'kraus',
      'qubits': [0],
      'params':

In [26]:
import numpy as np

angle = Parameter("angle")

qc = QuantumCircuit(2,1)
qc.cx(0,1)
qc.rx(angle,0)
qc.h(0)

#qc.measure_all()

qc.measure(0,0)
qc.measure(1,0)
print(qc)

qc_str_3 = qasm3.dumps(qc)
qc_str_3.splitlines()

#js = qasm_to_json(qc_str_3)
#js


          ┌───────────┐┌───┐┌─┐   
q_0: ──■──┤ Rx(angle) ├┤ H ├┤M├───
     ┌─┴─┐└───────────┘└───┘└╥┘┌─┐
q_1: ┤ X ├───────────────────╫─┤M├
     └───┘                   ║ └╥┘
c: 1/════════════════════════╩══╩═
                             0  0 


['OPENQASM 3.0;',
 'include "stdgates.inc";',
 'input float[64] angle_0;',
 'bit[1] c;',
 'qubit[2] q;',
 'cx q[0], q[1];',
 'rx(angle_0) q[0];',
 'h q[0];',
 'c[0] = measure q[0];',
 'c[0] = measure q[1];']

In [166]:
angle = Parameter("angle")


qc = QuantumCircuit(2,1)
qc.h(0)
qc.rx(angle,0)
qc.ry(2,1)
qc.cx(0,1)
qc.measure_all()

#len(qc.data)

#dir(qc.data[0])
#dir(qc.data[0].qubits[0])
qc.data[1].params[0]

Parameter(angle)

In [4]:
s = "abc;"
s.rstrip(";").split()

['abc']

In [167]:
def from_qc_to_json(qc):
    json_data = {
        "instructions":[]
    }
    for i in range(len(qc.data)):
        if qc.data[i].name == "barrier":
            pass
        elif qc.data[i].name != "measure":
            json_data["instructions"].append({"name":qc.data[i].name, 
                                              "qubits":[qc.data[i].qubits[j]._index for j in range(len(qc.data[i].qubits))],
                                              "params": "{}".format(qc.data[i].params)
                                             })
        else:
            json_data["instructions"].append({"name":qc.data[i].name, 
                                              "qubits":[qc.data[i].qubits[j]._index for j in range(len(qc.data[i].qubits))],
                                              "memory":[qc.data[i].clbits[j]._index for j in range(len(qc.data[i].clbits))]
                                             })

    return json_data
        

In [183]:
js = from_qc_to_json(qc)
type(js)
js_bin = pickle.dumps(js)
sys.getsizeof(qc), sys.getsizeof(js), sys.getsizeof(js_bin)
js_bin

AttributeError: 'bytes' object has no attribute 'size'

In [184]:
with open("js_normal.txt", "w") as js_normal:
    js_normal.write(str(js))

In [185]:
with open("js_bin.txt", "w") as js_binario:
    js_binario.write(str(js_bin))

In [2]:
__default_backends["ideal_aer"];

NameError: name '__default_backends' is not defined

In [ ]:
backend = Backend(name="fakeqmio")
#backend._backend_dict

In [18]:
d = {"0":0, "1":1}
d.keys()

dict_keys(['0', '1'])

NameError: name '_Backend__default_backends' is not defined

In [8]:
qpu = QPU(id_=0, server_endpoint="1")

Creating Ideal Aer Backend


NameError: name '_Backend__default_backends' is not defined

In [3]:
back = Backend(name="aer")
back.run(circ="a")

Instanciamos AerSimulator con los self.kwargs y le hacemos el run


In [4]:
qc = "Quantum Circuit"
dict = _get_dict(qc,back, shots=299, noise_model = {"0":"Primer ruido", "1":"Segundo ruido"})

In [8]:
dict_des = json.loads(dict["run_arguments"])

In [9]:
dict_des

{'shots': 299, 'noise_model': {'0': 'Primer ruido', '1': 'Segundo ruido'}}

In [10]:
dict_des["noise_model"]

{'0': 'Primer ruido', '1': 'Segundo ruido'}

In [5]:
!conda list

# packages in environment at /mnt/netapp1/Store_CESGA/home/cesga/acarballido/conda/envs/dask-simulator:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anyio                     4.6.2                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.0.5                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
aws-c-auth                0.7.22               h96bc93b_2    conda-forge
aws-c-cal                 0.6.14               h88a6e22_1    conda-forge
aws-c-common              0.9.19               h4ab18f5_0    conda-forge
aws-c-compression         0.2.18               h83b837d_6    conda

In [10]:
d = {"noise_model":"test_noise", "other_parameter":"test"}
back = Backend(noise_model = "test_noise", other_parameter = "test")

In [3]:
from qiskit_aer import AerSimulator

ModuleNotFoundError: No module named 'qiskit_aer'